"""empty message

Revision ID: 2110c2affa9e
Revises: 
Create Date: 2020-11-17 12:37:43.846838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2110c2affa9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_files', sa.Column('folder_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'uploaded_files', 'folders', ['folder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uploaded_files', type_='foreignkey')
    op.drop_column('uploaded_files', 'folder_id')
    # ### end Alembic commands ###
